apiVersion: v1
kind: Service
metadata:
  name: {APP_NAME}
spec:
  ports:
  - port: {EXPOSE_PORT}
    protocol: TCP
    targetPort: {PORT}
  sessionAffinity: None
  selector:
    app: {APP_NAME}
  type: NodePort